services:
  file-downloader:
    build:
      context: .
    command: uv run python src/file_downloader/download.py

  audio-mixer:
    build:
      context: .
    command: uv run python src/mixer/generate_audio.py

  publish-to-dropbox:
    build:
      context: .
    command: bash src/publish-podcast-to-dropbox/publish.sh

# Volumes will be defined in override files

