services:
  file-downloader:
    volumes:
      - ${COMPOSE_ENV_FILE:-./.env}:/app/.env:ro
      - voice-memos:/app/data/voice-memos

  audio-mixer:
    volumes:
      - ${COMPOSE_ENV_FILE:-./.env}:/app/.env:ro
      - ~/Dropbox/wafflebot/background-music:/app/data/background-music:ro
      - podcast-audio:/app/data/podcast
      - voice-memos:/app/data/voice-memos:ro

  publish-to-dropbox:
    volumes:
      - podcast-audio:/app/data/podcast:ro
      - ~/Dropbox/Apps/PushPod/Haotic\ Waffles:/app/dropbox-output

  publish-podcast-to-s3:
    volumes:
      - ${COMPOSE_ENV_FILE:-./.env}:/app/.env:ro
      - podcast-audio:/app/data/podcast:ro

  update-rss-feed:
    volumes:
      - ${COMPOSE_ENV_FILE:-./.env}:/app/.env:ro
      - rss-output:/app/data/rss

volumes:
  voice-memos:
  podcast-audio:
  rss-output: 