services:
  file-downloader:
    image: wafflebot:latest
    command: ["file-downloader"]

  audio-mixer:
    image: wafflebot:latest
    command: ["audio-mixer"]

  publish-to-dropbox:
    image: wafflebot:latest
    command: ["publish-to-dropbox"]

  publish-podcast-to-s3:
    image: wafflebot:latest
    command: ["publish-podcast-to-s3"]

  update-rss-feed:
    image: wafflebot:latest
    command: ["update-rss-feed"]
# Volumes will be defined in override files
