services:
  file-downloader:
    build:
      context: .
    volumes:
      - ./.env:/app/.env:ro
      - voice-memos:/app/data/voice-memos
    command: uv run python src/file_downloader/download.py

  audio-mixer:
    build:
      context: .
    volumes:
      - ./.env:/app/.env:ro
      - ~/Dropbox/wafflebot/background-music:/app/static/background-music:ro
      - ./data/podcast:/app/data/podcast
      - voice-memos:/app/data/voice-memos:ro
    command: uv run python src/mixer/generate_audio.py

volumes:
  voice-memos:

