services:
  audio-mixer:
    user: root
    volumes:
      - ./tests/.env.test:/app/.env:ro
      - ./tests/cache/voice-memos:/app/data/voice-memos:ro
      - ./tests/cache/background-music:/app/data/background-music:ro
      - ./tests/cache/test-outputs/podcast:/app/data/podcast

  publish-to-dropbox:
    user: root
    volumes:
      - ./tests/cache/test-outputs/podcast:/app/data/podcast:ro
      - ./tests/cache/test-outputs/dropbox:/app/dropbox-output

  publish-podcast-to-s3:
    volumes:
      - ./tests/.env.test:/app/.env:ro
      - ./tests/cache/test-outputs/podcast:/app/data/podcast:ro
    depends_on:
      - minio

  update-rss-feed:
    volumes:
      - ./tests/.env.test:/app/.env:ro
      - ./tests/cache/test-outputs/rss:/app/data/rss
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: testuser
      MINIO_ROOT_PASSWORD: testpassword
    command: server /data --console-address ":9001"
    volumes:
      - test-minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 1s
      timeout: 30s
      retries: 30

volumes:
  test-minio-data:
