services:
  file-downloader:
    env_file: ${COMPOSE_ENV_FILE}
    volumes:
      - voice-memos:/app/data/voice-memos

  audio-mixer:
    env_file: ${COMPOSE_ENV_FILE}
    volumes:
      - ${BACKGROUND_MUSIC_PATH}:/app/data/background-music:ro
      - podcast-audio:/app/data/podcast
      - voice-memos:/app/data/voice-memos:ro

  publish-to-dropbox:
    env_file: ${COMPOSE_ENV_FILE}
    volumes:
      - podcast-audio:/app/data/podcast:ro
      - type: bind
        source: ${DROPBOX_OUTPUT_PATH}
        target: /app/data/dropbox-output
        bind:
          create_host_path: false

  publish-podcast-to-s3:
    env_file:
      - ${COMPOSE_ENV_FILE}
      - ${COMPOSE_AWS_ENV_FILE}
    volumes:
      - podcast-audio:/app/data/podcast:ro

  update-rss-feed:
    env_file:
      - ${COMPOSE_ENV_FILE}
      - ${COMPOSE_AWS_ENV_FILE}
    volumes:
      - rss-output:/app/data/rss

volumes:
  voice-memos:
  podcast-audio:
  rss-output:
