[project]
name = "wafflebot"
version = "0.1.0"
description = "A Discord bot that collects voice memos and prepares them for podcast hosting."
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"

dependencies = [
    "discord.py>=2.0.0",
    "pydub>=0.25.1"
]
