[build-system]
requires = ["uv"]
build-backend = "uv.build"

[project]
name = "wafflebot"
version = "0.1.0"
description = "A Discord bot that collects voice memos and prepares them for podcast hosting."
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"

[project.dependencies]
discord.py = "^2.0.0"
pydub = "^0.25.1"

[tool.uv]
# Additional uv-specific configurations can go here
