name: "Python Setup"
description: "Sets up Python environment with uv"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: uv sync --locked
      shell: bash
