name: Lint

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup
      - name: Run Ruff Lint
        run: uv run ruff check .
      - name: Run Ruff Format Check
        run: uv run ruff format --check .
