name: Type Check

on:
  push:
    branches: [master]
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-setup
      - name: Run Pyright
        run: uv run pyright
